[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[opener]
edge = [
    { run = 'microsoft-edge-stable "$@"', desc = "Open with Edge", orphan = true  }
]

[open]
prepend_rules = [
    { name = "*.svg", use = "edit" },
    { mime = "image/svg+xml", use = "edit" },
    { name = "*.pdf", use = "edge" },
    { mime = "application/pdf", use = "edge" }
]
