[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"

[opener]
edge = [
    { run = 'microsoft-edge-stable "$@"', desc = "Open with Edge", orphan = true }
]

[open]
prepend_rules = [
    { url = "*.svg", use = "edit" },
    { mime = "image/svg+xml", use = "edit" },
    { url = "*.pdf", use = "edge" },
    { mime = "application/pdf", use = "edge" }
]
