[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[opener]
pdf = [
	# xdg-open이 비동기라서 pdf순서대로 열기 위해 sleep
	{ run = 'for f in "$@"; do xdg-open "$f" >/dev/null 2>&1 & sleep 0.1; done', desc = "Open PDFs sequentially", orphan = true }
]

[open]
prepend_rules = [
	{ name = "*.svg", use = "edit" },
    { mime = "image/svg+xml", use = "edit" },
	{ name = "*.pdf", use = "pdf" },
    { mime = "application/pdf", use = "pdf" }
]
