general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 510
    on-timeout = notify-send "Idle" "화면 자동꺼짐까지 90초"
}

listener {
    timeout = 540
    on-timeout = notify-send "Idle" "화면 자동꺼짐까지 60초"
}

listener {
    timeout = 570
    on-timeout = notify-send "Idle" "화면 자동꺼짐까지 30초"
}

listener {
    timeout = 600
    on-timeout = hyprlock & hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
