preload = /home/simtal/Pictures/wallpapers/hyprland1.png

# wallpaper {
#     monitor =
#     # path = /home/simtal/Pictures/wallpapers/bg0.jpg
#     path = /home/simtal/Pictures/wallpapers/hyprland1.png
#     fit_mode = cover 
# }

wallpaper = ,/home/simtal/Pictures/wallpapers/hyprland1.png

splash = false
ipc = on
