general {
    hide_cursor = false
    ignore_empty_input = true
    immediate_render = true
    fail_timeout = 500
}

auth {
    fingerprint:enabled = true
}

background {
    monitor = 
    path = ~/Pictures/wallpapers/bg_lock.jpg
}

# image {
#     monitor =
#     path = ~/Pictures/wallpapers/bg_space.jpg
#     size = 150
#     rounding = -1
#     border_size = 0
#     position = -800, -500
# }

input-field {
    monitor =
    size = 400, 50
    outline_thickness = 2
    fade_on_empty = true
    placeholder_text = <i>Input Password...</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = -5, -380
}

label {
    monitor =
    text = Touch ID or Enter Password
    color = rgba(242, 243, 244, 0.75)
    font_size = 13
    position = 0, -438
}

label {
    monitor =
    text = attempts: $ATTEMPTS $FAIL
    color = rgba(242, 243, 244, 0.75)
    font_size = 13
    # position = 10, 10
    # halign = left
    # valign = bottom
    position = 0, -470
}

label { # battery
    monitor =
    text = cmd[update:60000] echo "$(cat /sys/class/power_supply/BAT0/capacity)%"
    color = rgba(255, 255, 255, 1.0)
    font_size = 15
    position = -5, 0
    halign = right
    valign = top
}

label { # battery
  monitor =
  text = cmd[update:1000] echo "$(~/.config/hypr/Scripts/battery-status)‎"
  color = rgba(242, 243, 244, 0.75)
  font_size = 17
  position = -53, -1
  halign = right
  valign = top
}

label {
  monitor =
  text = $LAYOUT
  color = rgba(242, 243, 244, 0.75)
  font_size = 15
  position = -100, 0
  halign = right
  valign = top
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M:%S")"
    color = rgba(242, 243, 244, 0.75)
    font_size = 64
    font_family = Bold
    position = -5, 15
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %B %d")"
    color = rgba(242, 243, 244, 0.75)
    font_size = 20
    position = -5, -85
}
